import { IndicatorConfig } from "./types";

export const INDICATOR_REGISTRY: IndicatorConfig[] = [
  {
    id: "sma",
    name: "Moving Average",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1, max: 200 },
      {
        id: "method",
        name: "Moving average",
        type: "source",
        default: "SMA",
        options: ["SMA", "EMA", "WMA", "SMMA", "TMA"],
      },
      {
        id: "source",
        name: "Source",
        type: "source",
        default: "close",
        options: ["close", "open", "high", "low"],
      },
      { id: "color", name: "main", type: "color", default: "#34d399" },
      { id: "width", name: "width", type: "number", default: 1, min: 1, max: 5 },
    ],
    outputs: [{ id: "line", type: "line" }],
  },
  {
    id: "bollinger",
    name: "Bollinger Bands",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "period", name: "Period", type: "number", default: 20, min: 1, max: 200 },
      { id: "stdDev", name: "Deviation", type: "number", default: 2, min: 0.1, max: 10, step: 0.1 },
      { id: "upperColor", name: "top", type: "color", default: "#22c55e" },
      { id: "middleColor", name: "middle", type: "color", default: "#ef4444" },
      { id: "lowerColor", name: "bottom", type: "color", default: "#ef4444" },
      { id: "background", name: "background", type: "fill", default: "#facc15" },
    ],
    outputs: [
      { id: "upper", type: "line" },
      { id: "middle", type: "line" },
      { id: "lower", type: "line" },
    ],
  },
  {
    id: "alligator",
    name: "Alligator",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "jawPeriod", name: "Jaws Period", type: "number", default: 13, min: 1 },
      { id: "jawShift", name: "Jaws Shift", type: "number", default: 8, min: 0 },
      { id: "teethPeriod", name: "Teeth Period", type: "number", default: 8, min: 1 },
      { id: "teethShift", name: "Teeth Shift", type: "number", default: 5, min: 0 },
      { id: "lipsPeriod", name: "Lips Period", type: "number", default: 5, min: 1 },
      { id: "lipsShift", name: "Lips Shift", type: "number", default: 3, min: 0 },
      { id: "lipsColor", name: "lips", type: "color", default: "#22c55e" },
      { id: "teethColor", name: "teeth", type: "color", default: "#fb923c" },
      { id: "jawColor", name: "jaws", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "lips", type: "line" },
      { id: "teeth", type: "line" },
      { id: "jaw", type: "line" },
    ],
  },
  {
    id: "envelopes",
    name: "Envelopes",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "period", name: "Period", type: "number", default: 21, min: 1 },
      { id: "deviation", name: "Deviation", type: "number", default: 0.11, min: 0.01, step: 0.01 },
      {
        id: "method",
        name: "Moving average",
        type: "source",
        default: "SMA",
        options: ["SMA", "EMA", "WMA", "SMMA", "TMA"],
      },
      {
        id: "source",
        name: "Applied to",
        type: "source",
        default: "close",
        options: ["close", "open", "high", "low"],
      },
      { id: "upperColor", name: "top", type: "color", default: "#22c55e" },
      { id: "middleColor", name: "middle", type: "color", default: "#ef4444" },
      { id: "lowerColor", name: "bottom", type: "color", default: "#ef4444" },
      { id: "background", name: "background", type: "fill", default: "#facc15" },
    ],
    outputs: [
      { id: "upper", type: "line" },
      { id: "middle", type: "line" },
      { id: "lower", type: "line" },
    ],
  },
  {
    id: "fractal",
    name: "Fractal",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "period", name: "Period", type: "number", default: 2, min: 2, max: 8 },
      { id: "upColor", name: "up", type: "color", default: "#22c55e" },
      { id: "downColor", name: "down", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "up", type: "line" },
      { id: "down", type: "line" },
    ],
  },
  {
    id: "ichimoku",
    name: "Ichimoku Cloud",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "conversion", name: "Tenkan Sen", type: "number", default: 9, min: 1 },
      { id: "base", name: "Kijun Sen", type: "number", default: 26, min: 1 },
      { id: "spanB", name: "Senkou Span B", type: "number", default: 52, min: 1 },
      { id: "conversionColor", name: "tenkanSen", type: "color", default: "#22c55e" },
      { id: "baseColor", name: "kijunSen", type: "color", default: "#ef4444" },
      { id: "laggingColor", name: "chikouSpan", type: "color", default: "#ef4444" },
      { id: "spanAColor", name: "spanA", type: "color", default: "#facc15" },
      { id: "spanBColor", name: "spanB", type: "color", default: "#22d3ee" },
      { id: "background", name: "background", type: "fill", default: "#14b8a6" },
    ],
    outputs: [
      { id: "conversion", type: "line" },
      { id: "base", type: "line" },
      { id: "spanA", type: "line" },
      { id: "spanB", type: "line" },
      { id: "lagging", type: "line" },
    ],
  },
  {
    id: "keltner",
    name: "Keltner Channel",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "emaPeriod", name: "EMA Period", type: "number", default: 20, min: 1 },
      { id: "atrPeriod", name: "ATR Period", type: "number", default: 10, min: 1 },
      { id: "multiplier", name: "Multiplier", type: "number", default: 1, min: 0.1, step: 0.1 },
      { id: "upperColor", name: "top", type: "color", default: "#22c55e" },
      { id: "middleColor", name: "middle", type: "color", default: "#ef4444" },
      { id: "lowerColor", name: "bottom", type: "color", default: "#ef4444" },
      { id: "background", name: "background", type: "fill", default: "#facc15" },
    ],
    outputs: [
      { id: "upper", type: "line" },
      { id: "middle", type: "line" },
      { id: "lower", type: "line" },
    ],
  },
  {
    id: "donchian",
    name: "Donchian Channel",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "period", name: "Period", type: "number", default: 20, min: 1 },
      { id: "upperColor", name: "top", type: "color", default: "#22c55e" },
      { id: "middleColor", name: "middle", type: "color", default: "#ef4444" },
      { id: "lowerColor", name: "bottom", type: "color", default: "#ef4444" },
      { id: "background", name: "background", type: "fill", default: "#facc15" },
    ],
    outputs: [
      { id: "upper", type: "line" },
      { id: "middle", type: "line" },
      { id: "lower", type: "line" },
    ],
  },
  {
    id: "supertrend",
    name: "Supertrend",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "period", name: "Period", type: "number", default: 10, min: 1 },
      { id: "multiplier", name: "Multiplier", type: "number", default: 3, min: 0.1, step: 0.1 },
      { id: "upColor", name: "up", type: "color", default: "#22c55e" },
      { id: "downColor", name: "down", type: "color", default: "#ef4444" },
    ],
    outputs: [{ id: "trend", type: "line" }],
  },
  {
    id: "parabolic",
    name: "Parabolic SAR",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "step", name: "Acceleration", type: "number", default: 0.02, min: 0.001, step: 0.01 },
      { id: "max", name: "Max acceleration", type: "number", default: 0.2, min: 0.01, step: 0.01 },
      { id: "sarColor", name: "main", type: "color", default: "#22c55e" },
    ],
    outputs: [{ id: "sar", type: "line" }],
  },
  {
    id: "zigzag",
    name: "Zig Zag",
    category: "Trend Indicators",
    pane: "overlay",
    params: [
      { id: "deviation", name: "Deviation", type: "number", default: 5, min: 0.1, step: 0.1 },
      { id: "depth", name: "Depth", type: "number", default: 12, min: 2, max: 100 },
      { id: "backstep", name: "Backstep", type: "number", default: 3, min: 1, max: 100 },
      { id: "zagColor", name: "main", type: "color", default: "#66d10b" },
    ],
    outputs: [{ id: "zag", type: "line" }],
  },

  {
    id: "macd",
    name: "MACD",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "fast", name: "Fast period", type: "number", default: 12, min: 1 },
      { id: "slow", name: "Slow period", type: "number", default: 26, min: 1 },
      { id: "signal", name: "Signal period", type: "number", default: 9, min: 1 },
      { id: "histogramColor", name: "histogram", type: "color", default: "#1f2937" },
      { id: "macdColor", name: "macd", type: "color", default: "#22c55e" },
      { id: "signalColor", name: "signal", type: "color", default: "#ef4444" },
      { id: "histColorUp", name: "up", type: "color", default: "#22c55e" },
      { id: "histColorDown", name: "down", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "histogram", type: "histogram" },
      { id: "macd", type: "line" },
      { id: "signal", type: "line" },
    ],
  },
  {
    id: "rsi",
    name: "RSI",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1, max: 200 },
      { id: "overbought", name: "Overbought Level", type: "number", default: 70, min: 0, max: 100 },
      { id: "oversold", name: "Oversold Level", type: "number", default: 30, min: 0, max: 100 },
      { id: "overboughtColor", name: "overbought", type: "color", default: "#ef4444" },
      { id: "oversoldColor", name: "oversold", type: "color", default: "#ef4444" },
      { id: "lineColor", name: "main", type: "color", default: "#22c55e" },
    ],
    outputs: [
      { id: "line", type: "line" },
      { id: "overbought", type: "line" },
      { id: "oversold", type: "line" },
    ],
  },
  {
    id: "stochastic",
    name: "Stochastic Oscillator",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "kPeriod", name: "%K Period", type: "number", default: 14, min: 1 },
      { id: "dPeriod", name: "%D Period", type: "number", default: 3, min: 1 },
      { id: "slowing", name: "Smoothing period", type: "number", default: 3, min: 1 },
      { id: "overbought", name: "Overbought Level", type: "number", default: 70, min: 0, max: 100 },
      { id: "oversold", name: "Oversold Level", type: "number", default: 30, min: 0, max: 100 },
      {
        id: "method",
        name: "Moving average",
        type: "source",
        default: "SMA",
        options: ["SMA", "EMA"],
      },
      { id: "kColor", name: "kPeriod", type: "color", default: "#22c55e" },
      { id: "dColor", name: "dPeriod", type: "color", default: "#ef4444" },
      { id: "overboughtColor", name: "overbought", type: "color", default: "#ef4444" },
      { id: "oversoldColor", name: "oversold", type: "color", default: "#22d3ee" },
    ],
    outputs: [
      { id: "k", type: "line" },
      { id: "d", type: "line" },
      { id: "overbought", type: "line" },
      { id: "oversold", type: "line" },
    ],
  },
  {
    id: "adx",
    name: "ADX",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1 },
      { id: "adxColor", name: "adx", type: "color", default: "#22c55e" },
      { id: "pdiColor", name: "plusDI", type: "color", default: "#22c55e" },
      { id: "mdiColor", name: "minusDI", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "adx", type: "line" },
      { id: "pdi", type: "line" },
      { id: "mdi", type: "line" },
    ],
  },
  {
    id: "aroon",
    name: "Aroon",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1 },
      { id: "upColor", name: "up", type: "color", default: "#22c55e" },
      { id: "downColor", name: "down", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "up", type: "line" },
      { id: "down", type: "line" },
    ],
  },
  {
    id: "awesome",
    name: "Awesome Oscillator",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "fast", name: "Period Short", type: "number", default: 5, min: 1 },
      { id: "slow", name: "Period Long", type: "number", default: 34, min: 1 },
      { id: "histColorUp", name: "up", type: "color", default: "#22c55e" },
      { id: "histColorDown", name: "down", type: "color", default: "#ef4444" },
    ],
    outputs: [{ id: "histogram", type: "histogram" }],
  },
  {
    id: "cci",
    name: "CCI",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 20, min: 1 },
      { id: "lineColor", name: "main", type: "color", default: "#ef4444" },
      { id: "background", name: "background", type: "fill", default: "#ef4444" },
    ],
    outputs: [{ id: "line", type: "line" }],
  },
  {
    id: "momentum",
    name: "Momentum",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 10, min: 1 },
      { id: "lineColor", name: "main", type: "color", default: "#ef4444" },
    ],
    outputs: [{ id: "line", type: "line" }],
  },
  {
    id: "roc",
    name: "Rate Of Change",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1 },
      { id: "lineColor", name: "main", type: "color", default: "#ef4444" },
    ],
    outputs: [{ id: "line", type: "line" }],
  },
  {
    id: "williamsR",
    name: "Williams %R",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1 },
      { id: "lineColor", name: "main", type: "color", default: "#22c55e" },
      { id: "upperBandColor", name: "upperBand", type: "color", default: "#ef4444" },
      { id: "lowerBandColor", name: "lowerBand", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "line", type: "line" },
      { id: "upperBand", type: "line" },
      { id: "lowerBand", type: "line" },
    ],
  },
  {
    id: "demarker",
    name: "DeMarker",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1 },
      { id: "overbought", name: "Overbought", type: "number", default: 0.7, min: 0, max: 1, step: 0.01 },
      { id: "oversold", name: "Oversold", type: "number", default: 0.3, min: 0, max: 1, step: 0.01 },
      { id: "overboughtColor", name: "overbought", type: "color", default: "#22c55e" },
      { id: "oversoldColor", name: "oversold", type: "color", default: "#ef4444" },
      { id: "lineColor", name: "main", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "line", type: "line" },
      { id: "overbought", type: "line" },
      { id: "oversold", type: "line" },
    ],
  },
  {
    id: "bullsPower",
    name: "Bulls Power",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 13, min: 1 },
      { id: "lineColor", name: "main", type: "color", default: "#ef4444" },
    ],
    outputs: [{ id: "line", type: "line" }],
  },
  {
    id: "bearsPower",
    name: "Bears Power",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 13, min: 1 },
      { id: "lineColor", name: "main", type: "color", default: "#22c55e" },
    ],
    outputs: [{ id: "line", type: "line" }],
  },
  {
    id: "vortex",
    name: "Vortex",
    category: "Oscillators",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 14, min: 1 },
      { id: "viPlusColor", name: "viPlus", type: "color", default: "#ef4444" },
      { id: "viMinusColor", name: "viMinus", type: "color", default: "#ef4444" },
    ],
    outputs: [
      { id: "viPlus", type: "line" },
      { id: "viMinus", type: "line" },
    ],
  },

  {
    id: "atr",
    name: "ATR",
    category: "Volatility",
    pane: "separate",
    params: [
      { id: "period", name: "Period", type: "number", default: 10, min: 1 },
      { id: "lineColor", name: "main", type: "color", default: "#22c55e" },
    ],
    outputs: [{ id: "line", type: "line" }],
  },
  {
    id: "volumeOsc",
    name: "Volume Oscillator",
    category: "Volume",
    pane: "separate",
    params: [
      { id: "fast", name: "Fast period", type: "number", default: 5, min: 1 },
      { id: "slow", name: "Slow period", type: "number", default: 14, min: 1 },
      { id: "histColorUp", name: "up", type: "color", default: "#22c55e" },
      { id: "histColorDown", name: "down", type: "color", default: "#ef4444" },
    ],
    outputs: [{ id: "histogram", type: "histogram" }],
  },
];

export const STANDARD_INDICATOR_IDS = new Set([
  "sma",
  "bollinger",
  "alligator",
  "envelopes",
  "fractal",
  "ichimoku",
  "keltner",
  "donchian",
  "supertrend",
  "parabolic",
  "zigzag",
  "macd",
  "rsi",
  "stochastic",
  "adx",
  "aroon",
  "awesome",
  "cci",
  "momentum",
  "roc",
  "williamsR",
  "demarker",
  "bullsPower",
  "bearsPower",
  "vortex",
  "atr",
  "volumeOsc",
]);
