// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim() ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ?? "";
const FALLBACK_SUPABASE_URL = "https://placeholder.invalid";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "missing-publishable-key";
const SUPABASE_CLIENT_FETCH_TIMEOUT_MS = 12000;
const SUPABASE_AUTH_FETCH_TIMEOUT_MS = 45000;

type StorageLike = Pick<Storage, "getItem" | "setItem" | "removeItem">;

const createMemoryStorage = (): StorageLike => {
  const store = new Map<string, string>();

  return {
    getItem: (key) => store.get(key) ?? null,
    setItem: (key, value) => {
      store.set(key, value);
    },
    removeItem: (key) => {
      store.delete(key);
    },
  };
};

const resolveAuthStorage = (): StorageLike => {
  if (typeof window === "undefined") {
    return createMemoryStorage();
  }

  try {
    const storage = window.localStorage;
    const probeKey = "__supabase_storage_probe__";

    storage.setItem(probeKey, "1");
    storage.removeItem(probeKey);

    return storage;
  } catch {
    return createMemoryStorage();
  }
};

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
export const supabaseUrl = isSupabaseConfigured ? SUPABASE_URL : "";
export const supabasePublishableKey = isSupabaseConfigured ? SUPABASE_PUBLISHABLE_KEY : "";

if (!isSupabaseConfigured) {
  console.error("Supabase environment variables are missing. Falling back to a disabled client.");
}

const createTimeoutFetch =
  (timeoutMs: number, authTimeoutMs: number): typeof fetch =>
  async (input, init = {}) => {
    if (typeof AbortController === "undefined") {
      return fetch(input, init);
    }

    const url = typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
    const effectiveTimeoutMs = /\/auth\/v1\/(token|authorize|callback|verify|signup|recover|user)/i.test(url)
      ? authTimeoutMs
      : timeoutMs;
    const controller = new AbortController();
    const inheritedSignal = init.signal;
    const timeout = globalThis.setTimeout(() => controller.abort(), effectiveTimeoutMs);
    const abortFromInheritedSignal = () => controller.abort();

    if (inheritedSignal) {
      if (inheritedSignal.aborted) {
        controller.abort();
      } else {
        inheritedSignal.addEventListener("abort", abortFromInheritedSignal, { once: true });
      }
    }

    try {
      return await fetch(input, {
        ...init,
        signal: controller.signal,
      });
    } finally {
      globalThis.clearTimeout(timeout);
      inheritedSignal?.removeEventListener("abort", abortFromInheritedSignal);
    }
  };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  isSupabaseConfigured ? SUPABASE_URL : FALLBACK_SUPABASE_URL,
  isSupabaseConfigured ? SUPABASE_PUBLISHABLE_KEY : FALLBACK_SUPABASE_PUBLISHABLE_KEY,
  {
    global: {
      fetch: createTimeoutFetch(SUPABASE_CLIENT_FETCH_TIMEOUT_MS, SUPABASE_AUTH_FETCH_TIMEOUT_MS),
    },
    auth: {
      storage: resolveAuthStorage(),
      persistSession: isSupabaseConfigured,
      autoRefreshToken: isSupabaseConfigured,
      detectSessionInUrl: isSupabaseConfigured,
    },
  }
);
