// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim() ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ?? "";
const FALLBACK_SUPABASE_URL = "https://placeholder.invalid";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "missing-publishable-key";

type StorageLike = Pick<Storage, "getItem" | "setItem" | "removeItem">;

const createMemoryStorage = (): StorageLike => {
  const store = new Map<string, string>();

  return {
    getItem: (key) => store.get(key) ?? null,
    setItem: (key, value) => {
      store.set(key, value);
    },
    removeItem: (key) => {
      store.delete(key);
    },
  };
};

const resolveAuthStorage = (): StorageLike => {
  if (typeof window === "undefined") {
    return createMemoryStorage();
  }

  try {
    const storage = window.localStorage;
    const probeKey = "__supabase_storage_probe__";

    storage.setItem(probeKey, "1");
    storage.removeItem(probeKey);

    return storage;
  } catch {
    return createMemoryStorage();
  }
};

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error("Supabase environment variables are missing. Falling back to a disabled client.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  isSupabaseConfigured ? SUPABASE_URL : FALLBACK_SUPABASE_URL,
  isSupabaseConfigured ? SUPABASE_PUBLISHABLE_KEY : FALLBACK_SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: resolveAuthStorage(),
      persistSession: isSupabaseConfigured,
      autoRefreshToken: isSupabaseConfigured,
      detectSessionInUrl: isSupabaseConfigured,
    },
  }
);
